
name: Generic Workflow
on:
  push:
    branches: [features/*, main]
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2
      - name: Checkout from git repository
        run: git checkout ${{ github.ref }}
