
name: Generic SpringBoot Microservices Workflow
on:
  workflow_call:
    inputs:
      workflow_id:
        description: 'The ID of the workflow to run'
        required: false
        type: string
      inputs:
        description: 'The inputs for the workflow'
        required: false
        type: string

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from git repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
 
      
       
      
      - name: Static Code Analysis (Sonarqube)
        run: |
          echo "Static Code Analysis (Sonarqube)..."
          # Add your build and test commands here
      
      - name: Software Composition Analysis (Snyk)
        run: |
          echo "Software Composition Analysis (Snyk)..."
          # Add your build and test commands here
      
      - name: Unit Testing (JUnit)
        run: |
          echo "Unit Testing (JUnit)..."
          # Add your build and test commands here

      - name: Code Coverage (JaCoCo)
        run: |
          echo "Code Coverage (JaCoCo)..."
          # Add your build and test commands here

      - name: SonarQube Analysis
        run: |
          echo "SonarQube Analysis..."
          # Add your build and test commands here

      - name: Setup java 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
  
      - name: Build with Maven
        run: |
          mvn -B clean package
          echo 'Build completed'

  publish_artifacts:
    needs: test_and_build
    runs-on: ubuntu-latest

    steps:
      - name: Upload build artifacts
        run: |
          echo "Uploading compliance reports..."
      - name: GetPort
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: UPSERT
          identifier: some_identifier
          title: Some Title
          properties: '{}'
